use localsearch_core::{FilesystemEvent, VolumeId};
use serde::{Deserialize, Serialize};

use crate::PlatformResult;

/// Operating-system family behind a provider implementation.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PlatformFamily {
    /// Microsoft Windows.
    Windows,
    /// Apple macOS.
    MacOs,
    /// Linux distributions.
    Linux,
}

/// Preferred full-enumeration strategy exposed by an adapter.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum InitialScanMode {
    /// Provider can use a filesystem metadata index or equivalent fast enumeration.
    FastMetadataEnumeration,
    /// Provider recursively walks visible filesystem namespaces.
    FilesystemCrawl,
}

/// Incremental change-feed semantics exposed by an adapter.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ChangeTrackingMode {
    /// Provider currently supports authoritative snapshots but no incremental stream.
    SnapshotOnly,
    /// Durable object-oriented journal with resumable checkpoints.
    PersistentObjectJournal,
    /// Durable path-oriented stream with resumable checkpoints.
    PersistentPathStream,
    /// Process-lifetime watchers that can overflow and require reconciliation.
    EphemeralWatchers,
}

/// Privilege and consent model required by a platform adapter.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PrivilegeModel {
    /// A narrowly scoped elevated broker can improve coverage but is not always required.
    OptionalBroker,
    /// Platform privacy consent determines visible sources and cannot be bypassed.
    UserConsent,
    /// The adapter normally operates with the current user's permissions.
    CurrentUser,
}

/// Declared semantics used to select recovery and indexing policy.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct PlatformCapabilities {
    /// Provider operating-system family.
    pub platform: PlatformFamily,
    /// Full-enumeration strategy.
    pub initial_scan: InitialScanMode,
    /// Incremental change-feed semantics.
    pub change_tracking: ChangeTrackingMode,
    /// Required privilege and consent model.
    pub privilege_model: PrivilegeModel,
    /// Whether object identities remain stable across renames within a volume.
    pub stable_object_ids: bool,
    /// Whether multiple namespace links can refer to one object.
    pub hard_links: bool,
    /// Whether the provider can resume from history persisted outside this process.
    pub persistent_history: bool,
}

/// Platform-neutral description of one discovered filesystem volume.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct VolumeDescriptor {
    /// Canonical volume identity generated by the adapter.
    pub volume_id: VolumeId,
    /// User-facing volume name when available.
    pub display_name: Option<String>,
    /// Current mount points or roots encoded as display paths.
    pub mount_points: Vec<String>,
    /// Provider-reported filesystem family, such as `ntfs`, `apfs`, or `ext4`.
    pub filesystem: Option<String>,
    /// Whether the volume is removable.
    pub removable: bool,
    /// Whether storage is locally attached rather than a network mount.
    pub local: bool,
}

/// Opaque, provider-owned continuation point for a single volume.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ProviderCheckpoint {
    /// Stable adapter identifier used to reject checkpoints from another provider.
    pub provider_id: String,
    /// Adapter-defined checkpoint encoding version.
    pub format_version: u32,
    /// Volume whose stream is being continued.
    pub volume_id: VolumeId,
    /// Opaque provider payload; consumers persist but never interpret these bytes.
    pub opaque: Vec<u8>,
}

/// Result of a completed initial scan or reconciliation.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ScanSummary {
    /// Continuation point that follows every emitted observation.
    pub checkpoint: ProviderCheckpoint,
    /// Number of canonical events emitted into the sink.
    pub emitted_events: u64,
}

/// Result of one bounded incremental read.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ChangeBatch {
    /// Continuation point that follows every emitted event in this batch.
    pub checkpoint: ProviderCheckpoint,
    /// Number of canonical events emitted into the sink.
    pub emitted_events: u32,
    /// Whether the provider knows that more changes are immediately available.
    pub has_more: bool,
}

/// Consumer of canonical filesystem observations.
pub trait FilesystemEventSink {
    /// Accepts one idempotent event.
    ///
    /// # Errors
    ///
    /// Returns an error when the downstream pipeline cannot accept the event.
    fn emit(&mut self, event: FilesystemEvent) -> PlatformResult<()>;
}

impl<F> FilesystemEventSink for F
where
    F: FnMut(FilesystemEvent) -> PlatformResult<()>,
{
    fn emit(&mut self, event: FilesystemEvent) -> PlatformResult<()> {
        self(event)
    }
}

/// Adapter boundary for filesystem discovery, enumeration, changes, and reconciliation.
///
/// Implementations may use native async facilities internally. The boundary is intentionally
/// synchronous and pull-based so it does not commit the domain to an async runtime.
pub trait FilesystemProvider: Send + Sync {
    /// Returns stable provider capabilities.
    fn capabilities(&self) -> PlatformCapabilities;

    /// Discovers volumes currently visible to the provider.
    ///
    /// # Errors
    ///
    /// Returns a categorized platform error when discovery cannot be completed.
    fn discover_volumes(&self) -> PlatformResult<Vec<VolumeDescriptor>>;

    /// Emits a consistent initial observation stream for one volume.
    ///
    /// # Errors
    ///
    /// Returns a categorized platform error for access failures, lost continuity, cancellation,
    /// or sink backpressure.
    fn initial_scan(
        &self,
        volume: &VolumeDescriptor,
        sink: &mut dyn FilesystemEventSink,
    ) -> PlatformResult<ScanSummary>;

    /// Emits at most `maximum_events` changes after a saved checkpoint.
    ///
    /// # Errors
    ///
    /// Returns [`crate::PlatformErrorKind::InvalidCheckpoint`] for incompatible checkpoints and
    /// [`crate::PlatformErrorKind::SourceHistoryGap`] when reconciliation is required.
    fn read_changes(
        &self,
        checkpoint: &ProviderCheckpoint,
        maximum_events: u32,
        sink: &mut dyn FilesystemEventSink,
    ) -> PlatformResult<ChangeBatch>;

    /// Re-enumerates and emits the canonical state required to repair a volume projection.
    ///
    /// # Errors
    ///
    /// Returns a categorized platform error when reconciliation cannot complete safely.
    fn reconcile(
        &self,
        volume: &VolumeDescriptor,
        sink: &mut dyn FilesystemEventSink,
    ) -> PlatformResult<ScanSummary>;
}
